// ============================================================
//  COW MILK YIELD SYSTEM — WITH LCD + NTP + FIREBASE HISTORY
//  ESP32-S3 + RC522 + HX711 + 2 Buttons + LCD 1602A (I2C)
//  LCD: PCF8574T backpack | SDA=21 SCL=22 | Address=0x27
//  Session IDs auto-generated by Firebase (POST)
// ============================================================

#include <SPI.h>
#include <MFRC522.h>
#include <HX711.h>
#include <WiFi.h>
#include <WiFiManager.h>
#include <HTTPClient.h>
#include <ArduinoJson.h>
#include <Wire.h>
#include <LiquidCrystal_I2C.h>
#include <time.h>

// ── Firebase ─────────────────────────────────────────────────
#define FIREBASE_DB_URL "https://cow-milk-system-default-rtdb.europe-west1.firebasedatabase.app"

// ── NTP ──────────────────────────────────────────────────────
#define NTP_SERVER      "pool.ntp.org"
#define GMT_OFFSET_SEC   3600   // Algeria = UTC+1
#define DST_OFFSET_SEC   0

// ── LCD ──────────────────────────────────────────────────────
#define LCD_ADDR  0x27
#define SDA_PIN   21
#define SCL_PIN   22

// ── RC522 Pins ───────────────────────────────────────────────
#define SS_PIN   5
#define RST_PIN  4
#define SCK_PIN  18
#define MOSI_PIN 23
#define MISO_PIN 19

// ── HX711 Pins ───────────────────────────────────────────────
#define HX711_DOUT 16
#define HX711_SCK  17

// ── Button Pins ──────────────────────────────────────────────
#define BTN_ENTER 13   // Cow enters milking room
#define BTN_DONE  14   // Cow done milking

// ── Scale Calibration ────────────────────────────────────────
#define CALIBRATION_FACTOR -7050.0

// ── Cow Registry ─────────────────────────────────────────────
struct Cow {
  const char* uid;
  const char* name;
  float       dailyMilk;
  int         sessions;
};

#define NUM_COWS 3
Cow cows[NUM_COWS] = {
  { "8B1FA004", "Bessie", 0.0, 0 },
  { "09AE7D05", "Daisy",  0.0, 0 },
  { "AABBCCDD", "Molly",  0.0, 0 }
};

// ── Hardware Objects ─────────────────────────────────────────
MFRC522           rfid(SS_PIN, RST_PIN);
HX711             scale;
LiquidCrystal_I2C lcd(LCD_ADDR, 16, 2);

// ── State Machine ────────────────────────────────────────────
enum State { IDLE, WAITING_RFID, MEASURING };
State currentState = IDLE;
int   activeCow    = -1;

// ── Date tracking ────────────────────────────────────────────
char currentDate[12] = "";

// ── Edge-detection buttons ───────────────────────────────────
struct ButtonState {
  int           pin;
  bool          lastReading;
  bool          triggered;
  unsigned long lastDebounce;
};

ButtonState btn_enter = { BTN_ENTER, HIGH, false, 0 };
ButtonState btn_done  = { BTN_DONE,  HIGH, false, 0 };

// ============================================================
//  LCD HELPERS
// ============================================================

// Print two lines — clears screen first
// line1 max 16 chars, line2 optional
void lcdShow(const char* line1, const char* line2 = "") {
  lcd.clear();
  lcd.setCursor(0, 0);
  lcd.print(line1);
  if (strlen(line2) > 0) {
    lcd.setCursor(0, 1);
    lcd.print(line2);
  }
}

// Print a float value on line 2 with label and unit
// e.g. lcdValue("Milk: ", 4.25, " kg")
void lcdValue(const char* label, float val, const char* unit) {
  lcd.setCursor(0, 1);
  lcd.print(label);
  lcd.print(val, 2);
  lcd.print(unit);
  lcd.print("          ");   // clear trailing characters
}

// Scrolls a long cow name on line 2 if > 10 chars
// (simple truncation for 1602A 16-char limit)
void lcdCowLine(const char* name, const char* suffix) {
  lcd.setCursor(0, 1);
  char buf[17];
  snprintf(buf, sizeof(buf), "%-10s%s", name, suffix);
  lcd.print(buf);
}

// ============================================================
//  BUTTON — fires once per press (edge detection)
// ============================================================
bool buttonPressed(ButtonState &btn) {
  bool reading = digitalRead(btn.pin);

  if (reading != btn.lastReading)
    btn.lastDebounce = millis();

  bool fired = false;
  if (millis() - btn.lastDebounce > 50) {
    if (reading == LOW && !btn.triggered) {
      fired         = true;
      btn.triggered = true;
    }
    if (reading == HIGH)
      btn.triggered = false;
  }

  btn.lastReading = reading;
  return fired;
}

// ============================================================
//  WIFIMANAGER
// ============================================================
void connectWiFi() {
  WiFiManager wm;
  // wm.resetSettings(); // uncomment to forget saved WiFi

  wm.setConfigPortalTimeout(180);

  lcdShow("Connecting WiFi", "CowSystem-Setup");

  Serial.println("📶 Starting WiFiManager...");
  Serial.println("   No saved WiFi? Connect to: CowSystem-Setup");
  Serial.println("   Password: cow12345 → open 192.168.4.1");

  bool ok = wm.autoConnect("CowSystem-Setup", "cow12345");

  if (ok) {
    Serial.println("✅ WiFi connected!");
    Serial.print("   SSID: "); Serial.println(WiFi.SSID());
    Serial.print("   IP  : "); Serial.println(WiFi.localIP());

    lcdShow("WiFi Connected!", WiFi.localIP().toString().c_str());
    delay(2000);
  } else {
    Serial.println("⚠️  Config portal timed out — running offline.");
    lcdShow("WiFi Failed", "Offline mode");
    delay(2000);
  }
}

// ============================================================
//  MAINTAIN WIFI
// ============================================================
void maintainWiFi() {
  if (WiFi.status() != WL_CONNECTED) {
    Serial.println("📶 WiFi dropped — reconnecting...");
    WiFi.reconnect();
    unsigned long t = millis();
    while (WiFi.status() != WL_CONNECTED && millis() - t < 8000) {
      delay(500);
      Serial.print(".");
    }
    if (WiFi.status() == WL_CONNECTED)
      Serial.println("\n✅ WiFi reconnected.");
    else
      Serial.println("\n⚠️  Reconnect failed — will retry.");
  }
}

// ============================================================
//  NTP TIME SYNC
// ============================================================
void syncTime() {
  if (WiFi.status() != WL_CONNECTED) {
    Serial.println("⚠️  No WiFi — cannot sync time.");
    return;
  }

  lcdShow("Syncing time...", "Please wait");
  Serial.print("🕐 Syncing NTP time");
  configTime(GMT_OFFSET_SEC, DST_OFFSET_SEC, NTP_SERVER);

  struct tm t;
  unsigned long start = millis();
  while (!getLocalTime(&t) && millis() - start < 10000) {
    Serial.print(".");
    delay(500);
  }

  if (getLocalTime(&t)) {
    char buf[20];
    strftime(buf, sizeof(buf), "%Y-%m-%d %H:%M", &t);
    Serial.println("\n✅ Time synced: " + String(buf));
    lcdShow("Time Synced!", buf);
    delay(2000);
  } else {
    Serial.println("\n⚠️  NTP sync failed — uptime fallback.");
    lcdShow("NTP Failed", "Uptime fallback");
    delay(2000);
  }
}

// ============================================================
//  TIMESTAMPS
// ============================================================
String getDateString() {
  struct tm t;
  if (!getLocalTime(&t)) {
    char buf[12];
    sprintf(buf, "day-%lu", millis() / 86400000UL);
    return String(buf);
  }
  char buf[12];
  strftime(buf, sizeof(buf), "%Y-%m-%d", &t);
  return String(buf);
}

String getTimeString() {
  struct tm t;
  if (!getLocalTime(&t)) {
    unsigned long s = millis() / 1000;
    char buf[10];
    sprintf(buf, "%02lu:%02lu:%02lu", (s/3600)%24, (s/60)%60, s%60);
    return String(buf);
  }
  char buf[10];
  strftime(buf, sizeof(buf), "%H:%M:%S", &t);
  return String(buf);
}

// ============================================================
//  DAILY RESET
// ============================================================
void resetDailyTotals(const String& newDate) {
  Serial.println("📅 New day — resetting totals.");
  for (int i = 0; i < NUM_COWS; i++) {
    cows[i].dailyMilk = 0.0;
    cows[i].sessions  = 0;
  }
  newDate.toCharArray(currentDate, sizeof(currentDate));
  Serial.println("✅ Totals reset. Date: " + newDate);
}

void checkAndResetDate() {
  String today = getDateString();
  if (strlen(currentDate) == 0) {
    today.toCharArray(currentDate, sizeof(currentDate));
    Serial.print("📅 Date initialized: "); Serial.println(currentDate);
    return;
  }
  if (today != String(currentDate))
    resetDailyTotals(today);
}

// ============================================================
//  FIREBASE REST — PUT
// ============================================================
bool firebasePut(const String& path, const String& json) {
  if (WiFi.status() != WL_CONNECTED) return false;

  HTTPClient http;
  http.begin(String(FIREBASE_DB_URL) + path + ".json");
  http.addHeader("Content-Type", "application/json");
  int code = http.PUT(json);
  bool ok  = (code == 200 || code == 204);
  if (!ok) {
    Serial.print("   ❌ PUT failed. HTTP: "); Serial.print(code);
    Serial.print(" → "); Serial.println(http.getString());
  }
  http.end();
  return ok;
}

// ============================================================
//  FIREBASE REST — POST (Firebase generates session ID)
// ============================================================
bool firebasePost(const String& path, const String& json) {
  if (WiFi.status() != WL_CONNECTED) return false;

  HTTPClient http;
  http.begin(String(FIREBASE_DB_URL) + path + ".json");
  http.addHeader("Content-Type", "application/json");
  int code = http.POST(json);
  bool ok  = (code == 200 || code == 204);
  if (!ok) {
    Serial.print("   ❌ POST failed. HTTP: "); Serial.print(code);
    Serial.print(" → "); Serial.println(http.getString());
  }
  http.end();
  return ok;
}

// ============================================================
//  SEND TO FIREBASE
// ============================================================
void sendToFirebase(int cowIdx, float sessionKg) {
  if (WiFi.status() != WL_CONNECTED) {
    Serial.println("⚠️  No WiFi — data NOT sent.");
    lcdShow("No WiFi!", "Data not saved");
    delay(2000);
    return;
  }

  Cow&   cow  = cows[cowIdx];
  String date = getDateString();
  String time = getTimeString();

  Serial.println("📤 Sending to Firebase...");
  lcdShow("Uploading...", "Please wait");

  // ── 1. Daily history per cow ─────────────────────────────────
  // Path: /cows/Bessie/history/2025-05-19
  StaticJsonDocument<192> histDoc;
  histDoc["uid"]           = cow.uid;
  histDoc["daily_milk_kg"] = serialized(String(cow.dailyMilk, 3));
  histDoc["sessions"]      = cow.sessions;
  histDoc["last_updated"]  = time;

  String histJson;
  serializeJson(histDoc, histJson);

  bool ok1 = firebasePut(
    "/cows/" + String(cow.name) + "/history/" + date,
    histJson
  );
  Serial.println(ok1 ? "   ✅ History updated." : "   ❌ History failed.");

  // ── 2. Individual session log ─────────────────────────────────
  // Path: /sessions/2025-05-19/{Firebase auto ID}
  // Firebase generates a unique push ID via POST — no manual key needed
  StaticJsonDocument<192> sessionDoc;
  sessionDoc["cow"]         = cow.name;
  sessionDoc["uid"]         = cow.uid;
  sessionDoc["milk_kg"]     = serialized(String(sessionKg, 3));
  sessionDoc["session_num"] = cow.sessions;
  sessionDoc["date"]        = date;
  sessionDoc["time"]        = time;

  String sessionJson;
  serializeJson(sessionDoc, sessionJson);

  bool ok2 = firebasePost(
    "/sessions/" + date,
    sessionJson
  );
  Serial.println(ok2 ? "   ✅ Session pushed." : "   ❌ Session failed.");

  // ── Show result on LCD ────────────────────────────────────────
  if (ok1 && ok2) {
    lcdShow("Firebase  OK!", "Data saved");
  } else {
    lcdShow("Firebase Error", "Check serial");
  }
  delay(2000);
}

// ============================================================
//  HELPERS
// ============================================================
String getUID() {
  String uid = "";
  for (byte i = 0; i < rfid.uid.size; i++) {
    if (rfid.uid.uidByte[i] < 0x10) uid += "0";
    uid += String(rfid.uid.uidByte[i], HEX);
  }
  uid.toUpperCase();
  return uid;
}

int findCowByUID(const String& uid) {
  for (int i = 0; i < NUM_COWS; i++) {
    if (uid.equalsIgnoreCase(cows[i].uid)) return i;
  }
  return -1;
}

void printSeparator() { Serial.println("============================"); }

void printDailySummary() {
  Serial.println("\n──── DAILY SUMMARY ── " + getDateString() + " ──");
  for (int i = 0; i < NUM_COWS; i++) {
    Serial.print("  ");
    Serial.print(cows[i].name);
    Serial.print(" ["); Serial.print(cows[i].uid); Serial.print("]: ");
    Serial.print(cows[i].dailyMilk, 3);
    Serial.print(" kg  (");
    Serial.print(cows[i].sessions);
    Serial.println(" sessions)");
  }
  Serial.println("──────────────────────────────────────\n");
}

// ============================================================
//  SHOW IDLE SCREEN — date + time on LCD
// ============================================================
void showIdleScreen() {
  lcd.clear();
  lcd.setCursor(0, 0);
  lcd.print("Scan RFID or");
  lcd.setCursor(0, 1);
  lcd.print("press BTN1 ");
  lcd.print(getTimeString().substring(0, 5));  // shows HH:MM
}

// ============================================================
//  SETUP
// ============================================================
void setup() {
  Serial.begin(115200);
  delay(1000);
  Serial.println("\n🐄 Cow Milk System Starting...");
  printSeparator();

  // ── Buttons ──────────────────────────────────────────────────
  pinMode(BTN_ENTER, INPUT_PULLUP);
  pinMode(BTN_DONE,  INPUT_PULLUP);

  // ── LCD ──────────────────────────────────────────────────────
  Wire.begin(SDA_PIN, SCL_PIN);
  Wire.setClock(100000);
  lcd.init();
  lcd.init();          // double init for reliability on ESP32-S3
  lcd.backlight();
  lcdShow("Milk System", "Starting...");
  delay(1500);
  Serial.println("✅ LCD ready.");

  // ── RFID ─────────────────────────────────────────────────────
  SPI.begin(SCK_PIN, MISO_PIN, MOSI_PIN, SS_PIN);
  rfid.PCD_Init();
  delay(100);
  byte v = rfid.PCD_ReadRegister(rfid.VersionReg);
  if (v == 0x00 || v == 0xFF) {
    Serial.println("❌ RC522 not detected!");
    lcdShow("RC522 Error!", "Check wiring");
    delay(3000);
  } else {
    Serial.print("✅ RC522 detected (v0x"); Serial.print(v, HEX); Serial.println(")");
    lcdShow("RFID Ready", "");
    delay(1000);
  }

  // ── HX711 ────────────────────────────────────────────────────
  scale.begin(HX711_DOUT, HX711_SCK);
  delay(2000);
  if (!scale.is_ready()) {
    Serial.println("❌ HX711 not ready!");
    lcdShow("HX711 Error!", "Check wiring");
    while (true) delay(1000);
  }
  scale.set_scale(CALIBRATION_FACTOR);
  scale.tare();
  Serial.println("✅ HX711 ready and tared.");
  lcdShow("Scale Ready", "Tared OK");
  delay(1000);

  // ── WiFi ─────────────────────────────────────────────────────
  connectWiFi();

  // ── NTP ──────────────────────────────────────────────────────
  syncTime();

  // ── Date init ────────────────────────────────────────────────
  checkAndResetDate();

  printSeparator();
  Serial.println("✅ System Ready!");
  Serial.print("   Today: "); Serial.println(currentDate);
  Serial.println("   BTN 13 = Cow ENTERS");
  Serial.println("   BTN 14 = Cow DONE");
  printSeparator();

  showIdleScreen();
}

// ============================================================
//  MAIN LOOP
// ============================================================
void loop() {

  maintainWiFi();

  // Check date change every 30 seconds
  static unsigned long lastDateCheck = 0;
  if (millis() - lastDateCheck > 30000) {
    lastDateCheck = millis();
    checkAndResetDate();
  }

  // Refresh idle screen clock every 30 seconds
  static unsigned long lastClockRefresh = 0;
  if (currentState == IDLE && millis() - lastClockRefresh > 30000) {
    lastClockRefresh = millis();
    showIdleScreen();
  }

  // ── IDLE ───────────────────────────────────────────────────
  if (currentState == IDLE) {
    if (buttonPressed(btn_enter)) {
      Serial.println("\n🔵 Cow entering — scan RFID tag...");
      lcdShow("Cow entering...", "Scan RFID tag");
      currentState = WAITING_RFID;
      activeCow    = -1;
    }
  }

  // ── WAITING_RFID ───────────────────────────────────────────
  else if (currentState == WAITING_RFID) {

    // BTN_ENTER again = cancel
    if (buttonPressed(btn_enter)) {
      Serial.println("↩️  Cancelled.\n");
      lcdShow("Cancelled", "");
      delay(1000);
      showIdleScreen();
      currentState = IDLE;
      return;
    }

    if (!rfid.PICC_IsNewCardPresent()) { delay(50); return; }
    if (!rfid.PICC_ReadCardSerial())   { delay(50); return; }

    String uid = getUID();
    Serial.print("📡 RFID scanned: "); Serial.println(uid);

    int idx = findCowByUID(uid);

    if (idx >= 0) {
      activeCow = idx;
      Cow& cow  = cows[activeCow];

      printSeparator();
      Serial.print("✅ Identified: "); Serial.print(cow.name);
      Serial.print("  ["); Serial.print(cow.uid); Serial.println("]");

      // Show cow name on LCD
      lcdShow(cow.name, "Taring scale...");
      delay(1000);

      scale.tare();
      delay(500);

      Serial.println("✅ Scale tared. Milking in progress...");
      Serial.println("   Press BTN 14 when done.\n");

      // LCD: show cow + live weight label
      lcd.clear();
      lcd.setCursor(0, 0);

      // Truncate name to fit 16 chars with " Milking"
      char topLine[17];
      snprintf(topLine, sizeof(topLine), "%-8s Milkg", cow.name);
      lcd.print(topLine);
      lcd.setCursor(0, 1);
      lcd.print("Live: 0.000 kg");

      currentState = MEASURING;

    } else {
      Serial.print("❓ Unknown UID: "); Serial.println(uid);
      lcdShow("Unknown tag!", "Scan again");
      Serial.println("   Add UID to cows[] array.");
      delay(2000);
      lcdShow("Cow entering...", "Scan RFID tag");
    }

    rfid.PICC_HaltA();
    rfid.PCD_StopCrypto1();
  }

  // ── MEASURING ──────────────────────────────────────────────
  else if (currentState == MEASURING) {

    // Live weight update every 1 second
    static unsigned long lastPrint = 0;
    if (millis() - lastPrint > 1000) {
      lastPrint = millis();

      float live = scale.get_units(5);
      if (live < 0) live = 0;

      // Serial
      Serial.print("  ⚖️  Live: ");
      Serial.print(live, 3);
      Serial.println(" kg");

      // LCD line 2: live weight
      lcd.setCursor(0, 1);
      lcd.print("Live:");
      lcd.print(live, 3);
      lcd.print(" kg   ");
    }

    if (buttonPressed(btn_done)) {
      float sessionKg = scale.get_units(10);
      if (sessionKg < 0) sessionKg = 0;

      Cow& cow = cows[activeCow];
      cow.dailyMilk += sessionKg;
      cow.sessions++;

      // ── Serial log ─────────────────────────────────────────
      printSeparator();
      Serial.print("✅ Done: ");            Serial.println(cow.name);
      Serial.print("   UID          : ");   Serial.println(cow.uid);
      Serial.print("   This session : ");   Serial.print(sessionKg, 3);     Serial.println(" kg");
      Serial.print("   Daily total  : ");   Serial.print(cow.dailyMilk, 3); Serial.println(" kg");
      Serial.print("   Sessions today: ");  Serial.println(cow.sessions);
      Serial.print("   Date         : ");   Serial.println(getDateString());
      Serial.print("   Time         : ");   Serial.println(getTimeString());
      printSeparator();

      // ── LCD: show session result ────────────────────────────
      // Screen 1: this session
      lcd.clear();
      lcd.setCursor(0, 0);
      char s1[17];
      snprintf(s1, sizeof(s1), "%-8s Done!", cow.name);
      lcd.print(s1);
      lcdValue("Got: ", sessionKg, " kg");
      delay(3000);

      // Screen 2: daily total
      lcd.clear();
      lcd.setCursor(0, 0);
      lcd.print("Daily total:");
      lcdValue("", cow.dailyMilk, " kg");
      delay(3000);

      // Screen 3: session count
      lcd.clear();
      lcd.setCursor(0, 0);
      lcd.print("Sessions today:");
      lcd.setCursor(0, 1);
      lcd.print(cow.sessions);
      lcd.print(" session");
      if (cow.sessions > 1) lcd.print("s");
      delay(2000);

      // ── Firebase ───────────────────────────────────────────
      sendToFirebase(activeCow, sessionKg);
      printDailySummary();

      activeCow    = -1;
      currentState = IDLE;
      Serial.println("Waiting... Press BTN 13 when next cow enters.\n");
      showIdleScreen();
    }
  }
}